# Generated by scripts/release/updateTap.ts in jrpat/jif — do not edit by hand.
class Jif < Formula
  desc "Keyboard-first terminal UI for Jujutsu"
  homepage "https://github.com/jrpat/jif"
  license "MIT"
  version "0.8.1"

  depends_on "jj"

  on_macos do
    on_arm do
      url "https://github.com/jrpat/jif/releases/download/v0.8.1/jif-v0.8.1-darwin-arm64.tar.gz"
      sha256 "83bb4f31684d17bf534b2b234090113d7210d73a03790aaf30bcee27a6ec305c"
    end
    on_intel do
      url "https://github.com/jrpat/jif/releases/download/v0.8.1/jif-v0.8.1-darwin-x64.tar.gz"
      sha256 "54592a732be4e4a71e1c33af7de2767429559d8301bd93292cb470faa309717e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jrpat/jif/releases/download/v0.8.1/jif-v0.8.1-linux-arm64.tar.gz"
      sha256 "9f8ad02777c7a994ba16183e6dc26a544c25f2742b264eeb04a4bccfa0a79add"
    end
    on_intel do
      url "https://github.com/jrpat/jif/releases/download/v0.8.1/jif-v0.8.1-linux-x64.tar.gz"
      sha256 "b97cf33812eb06b15fbae3a7de3d149a4c0a5234a2393e06078e999f1b132207"
    end
  end

  def install
    bin.install "jif"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jif --version")
  end
end
